# Koyeb deployment configuration
name: barber-backend-api

services:
  - name: api
    type: web
    git:
      branch: main
    instance_type: nano
    regions:
      - fra
    env:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8000"
      - key: HOST
        value: "0.0.0.0"
    build:
      command: npm install
    run:
      command: npm start
    health_check:
      path: /
      port: 8000
      initial_delay: 30
      timeout: 10
      interval: 30
    scaling:
      min: 1
      max: 1